field: aad2b36a-0613-4642-a7fa-88355cec07dc
fieldLayouts:
  f1bf6554-7130-4cd1-b399-0c238727b7ef:
    tabs:
      -
        elements:
          -
            fieldUid: 4be0f826-d972-4ca6-be81-63c8f82f0ba0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7a5bfb80-215c-4a0b-9fda-20f562bf605c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e8307b65-b5fb-4156-a905-d80f9b97db67
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4be0f826-d972-4ca6-be81-63c8f82f0ba0:
    contentColumnType: string
    fieldGroup: null
    handle: bilder
    instructions: ''
    name: Bilder
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      singleUploadLocationSubpath: bilder
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  7a5bfb80-215c-4a0b-9fda-20f562bf605c:
    contentColumnType: text
    fieldGroup: null
    handle: bildunterschriften
    instructions: ''
    name: Bildunterschriften
    searchable: false
    settings:
      addRowLabel: 'Bildunterschrift hinzuf√ºgen'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - ''
                -
                  - handle
                  - bildunterschrift
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  e8307b65-b5fb-4156-a905-d80f9b97db67:
    contentColumnType: text
    fieldGroup: null
    handle: galerietext
    instructions: ''
    name: Galerietext
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: erweitert.json
      removeEmptyTags: '1'
      removeInlineStyles: ''
      removeNbsp: ''
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: galerie
name: Galerie
sortOrder: 4
